title: EL OMARI Lokmane # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently Big Data Engineer at SFR, expert in data engineering and full-stack technologies. 
  <br><br>
  Driven by a deep-seated passion for technology, I, Lokman, embarked on my journey in the tech world with a Master's degree in Computer Science. This academic pursuit laid the groundwork for my career as a Full Stack Developer, where I've honed my skills in a diverse array of technologies, from backend frameworks like Django and Flask to frontend libraries such as React and Angular. My professional path has been marked by significant projects, including a pivotal role in deploying ML models in Málaga and currently enhancing data processes at SFR in France. My enthusiasm for full-stack development is not just about coding; it's about creating solutions that drive innovation and efficiency, reflecting my commitment to continuous learning and excellence in the ever-evolving tech landscape
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
